### ISSUE TITLE
Can I submit a localization (Simplified Chinese) update?

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/xsharp-notebooks#2]
I like this project very much. I hope people in the Chinese-speaking world can understand and use X# through it.

Due to my level of knowledge, I don't know how to load the Visual FoxPro dialect in the code of the notebook so that I can present the concepts expressed using the authentic VFP syntax.

Thanks in advance for the reply!

**Comment by fforay** [comment]
@RobertvanderHulst Thanks for merging the Pull Request, I didn't see it.

@vfp9 Many thanks for the translation !! As you can see, this is a Work-In-Progress : My goal is to provide a way to easily start with XSharp, but also learn some new tech with XSharp. With regards to the VFP dialect, this is in my To-Do list.
